### ISSUE TITLE
What's the meaning of chunks？

### ISSUE THREAD

**Issue by Gray-ly** [dgaddy/silent_speech#6]
Thanks for your contribution！I‘m a beginner for the research of EMG to Speech. Could you tell me something about the chunks in the info.json? I noticed it’s used in batch_length, but I don't know what's chunks and its source in data collection. Looking forward to your reply very much.

**Comment by dgaddy** [comment]
When recording signals the program receives values in batches rather than one at a time.  The "chunks" values in the info file just records the length of each of these chunks.  The chunk sizes themselves don't have any semantic meaning and can generally be ignored.    During batching these values are used to get the total length of the recording by taking their sum.
